"""Evidence storage and the audit export package (spec sections 91 and 92).

The export must let an auditor reproduce and challenge the result without
access to any hidden model reasoning. Everything it contains is deterministic
and human-readable.
"""

from __future__ import annotations

import csv
import hashlib
import io
import json
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any
from uuid import UUID

from packages.audit.events import AuditEvent
from packages.domain.dates import utc_now
from packages.domain.models.exceptions import Evidence, ExceptionRecord
from packages.domain.models.matching import MatchGroup
from packages.domain.models.reconciliation import (
    CloseCertificate,
    ReconciliationConfig,
    RunSnapshot,
    RunSummary,
)
from packages.domain.models.transaction import CanonicalTransaction

__all__ = [
    "AuditPackage",
    "EvidenceMetadata",
    "build_audit_package",
    "sha256_bytes",
]

# File types a finance team actually attaches. Anything else is rejected at
# upload rather than stored and hoped for (spec section 53).
ALLOWED_EVIDENCE_MIME_TYPES = frozenset(
    {
        "application/pdf",
        "image/png",
        "image/jpeg",
        "image/tiff",
        "text/csv",
        "text/plain",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "application/vnd.ms-excel",
        "message/rfc822",
        "application/json",
    }
)

MAX_EVIDENCE_BYTES = 50 * 1024 * 1024


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


@dataclass(frozen=True, slots=True)
class EvidenceMetadata:
    filename: str
    mime_type: str
    byte_size: int
    sha256: str

    @classmethod
    def inspect(cls, filename: str, mime_type: str, data: bytes) -> EvidenceMetadata:
        if mime_type not in ALLOWED_EVIDENCE_MIME_TYPES:
            raise ValueError(f"evidence type not allowed: {mime_type}")
        if len(data) > MAX_EVIDENCE_BYTES:
            raise ValueError(
                f"evidence exceeds the {MAX_EVIDENCE_BYTES // (1024 * 1024)}MB limit"
            )
        if not data:
            raise ValueError("evidence file is empty")
        return cls(
            filename=filename,
            mime_type=mime_type,
            byte_size=len(data),
            sha256=sha256_bytes(data),
        )


@dataclass(slots=True)
class AuditPackage:
    """The set of files that make up an audit export."""

    files: dict[str, bytes] = field(default_factory=dict)
    manifest: dict[str, str] = field(default_factory=dict)

    def add(self, name: str, content: bytes | str) -> None:
        data = content.encode("utf-8") if isinstance(content, str) else content
        self.files[name] = data
        self.manifest[name] = sha256_bytes(data)

    def manifest_json(self) -> str:
        return json.dumps(
            {"files": self.manifest, "generated_at": utc_now().isoformat()},
            indent=2,
            sort_keys=True,
        )


def _csv(rows: list[dict[str, Any]], columns: list[str]) -> str:
    buffer = io.StringIO(newline="")
    writer = csv.DictWriter(buffer, fieldnames=columns, extrasaction="ignore")
    writer.writeheader()
    for row in rows:
        writer.writerow(row)
    return buffer.getvalue()


def build_audit_package(
    *,
    summary: RunSummary,
    snapshot: RunSnapshot,
    config: ReconciliationConfig,
    matches: list[MatchGroup],
    exceptions: list[ExceptionRecord],
    transactions: dict[UUID, CanonicalTransaction],
    audit_events: list[AuditEvent],
    evidence: list[Evidence],
    certificate: CloseCertificate | None = None,
    generated_at: datetime | None = None,
) -> AuditPackage:
    """Assemble the export described in spec section 91.

    Every file is derived from stored state, never regenerated by re-running the
    engine, so the package describes what actually happened.
    """
    package = AuditPackage()
    stamp = generated_at or utc_now()

    package.add(
        "reconciliation-summary.json",
        json.dumps(
            {
                "generated_at": stamp.isoformat(),
                "summary": summary.model_dump(mode="json"),
                "snapshot": snapshot.model_dump(mode="json"),
                "close_certificate": (
                    certificate.model_dump(mode="json") if certificate else None
                ),
            },
            indent=2,
            sort_keys=True,
            default=str,
        ),
    )

    package.add(
        "source-manifest.csv",
        _csv(
            [
                {
                    "transaction_id": str(tx.id),
                    "source_system": tx.source_system,
                    "source_connection_id": str(tx.source_connection_id),
                    "source_record_id": tx.source_record_id,
                    "source_checksum": tx.source_checksum,
                    "imported_at": tx.imported_at.isoformat(),
                    "amount": str(tx.amount),
                    "currency": tx.currency,
                }
                for tx in sorted(transactions.values(), key=lambda t: str(t.id))
            ],
            [
                "transaction_id",
                "source_system",
                "source_connection_id",
                "source_record_id",
                "source_checksum",
                "imported_at",
                "amount",
                "currency",
            ],
        ),
    )

    package.add(
        "matched-items.csv",
        _csv(
            [
                {
                    "match_group_id": str(group.id),
                    "cardinality": group.cardinality.value,
                    "status": group.status.value,
                    "decision": group.decision.value,
                    "confidence": f"{group.confidence:.6f}",
                    "score": f"{group.score:.6f}",
                    "currency": group.currency,
                    "total_amount": str(group.total_amount),
                    "rule": f"{group.rule_id}:{group.rule_version}",
                    "rule_set_version": group.rule_set_version or "",
                    "model_version": group.model_version or "",
                    "engine_stage": group.engine_stage,
                    "competing_candidates": group.competing_candidate_count,
                    "side_a_transactions": " ".join(str(i) for i in group.side_a_ids),
                    "side_b_transactions": " ".join(str(i) for i in group.side_b_ids),
                    "reason_codes": " ".join(r.code for r in group.reasons),
                    "explanation": " ".join(r.description for r in group.reasons),
                    "warnings": " ".join(w.code for w in group.warnings),
                    "approved_by": str(group.approved_by) if group.approved_by else "",
                    "approved_at": (
                        group.approved_at.isoformat() if group.approved_at else ""
                    ),
                    "override_reason": group.override_reason or "",
                }
                for group in sorted(matches, key=lambda g: str(g.id))
            ],
            [
                "match_group_id",
                "cardinality",
                "status",
                "decision",
                "confidence",
                "score",
                "currency",
                "total_amount",
                "rule",
                "rule_set_version",
                "model_version",
                "engine_stage",
                "competing_candidates",
                "side_a_transactions",
                "side_b_transactions",
                "reason_codes",
                "explanation",
                "warnings",
                "approved_by",
                "approved_at",
                "override_reason",
            ],
        ),
    )

    package.add(
        "exceptions.csv",
        _csv(
            [
                {
                    "exception_id": str(item.id),
                    "category": item.category.value,
                    "severity": item.severity.value,
                    "status": item.status.value,
                    "amount_exposure": (
                        str(item.amount_exposure) if item.amount_exposure else ""
                    ),
                    "currency": item.currency or "",
                    "owner": str(item.owner_user_id) if item.owner_user_id else "",
                    "first_detected_at": item.first_detected_at.isoformat(),
                    "due_at": item.due_at.isoformat() if item.due_at else "",
                    "resolution_code": item.resolution_code or "",
                    "proposed_resolution": item.proposed_resolution or "",
                    "proposed_by": item.proposed_by_actor_type or "",
                    "closed_by": str(item.closed_by) if item.closed_by else "",
                    "closed_at": item.closed_at.isoformat() if item.closed_at else "",
                    "transactions": " ".join(str(i) for i in item.transaction_ids),
                }
                for item in sorted(exceptions, key=lambda e: str(e.id))
            ],
            [
                "exception_id",
                "category",
                "severity",
                "status",
                "amount_exposure",
                "currency",
                "owner",
                "first_detected_at",
                "due_at",
                "resolution_code",
                "proposed_resolution",
                "proposed_by",
                "closed_by",
                "closed_at",
                "transactions",
            ],
        ),
    )

    package.add(
        "approvals.csv",
        _csv(
            [
                {
                    "match_group_id": str(group.id),
                    "status": group.status.value,
                    "approved_by": str(group.approved_by) if group.approved_by else "",
                    "approved_at": (
                        group.approved_at.isoformat() if group.approved_at else ""
                    ),
                    "override_reason": group.override_reason or "",
                    "amount": str(group.total_amount),
                    "currency": group.currency,
                }
                for group in sorted(matches, key=lambda g: str(g.id))
                if group.approved_by is not None
            ],
            [
                "match_group_id",
                "status",
                "approved_by",
                "approved_at",
                "override_reason",
                "amount",
                "currency",
            ],
        ),
    )

    package.add(
        "rule-config.json",
        json.dumps(config.model_dump(mode="json"), indent=2, sort_keys=True, default=str),
    )

    package.add(
        "model-config.json",
        json.dumps(
            {
                "model_version": snapshot.model_version,
                "rule_set_version": snapshot.rule_set_version,
                "rule_versions": snapshot.rule_versions,
                "config_version": snapshot.config_version,
                "config_hash": snapshot.config_hash,
                "snapshot_hash": snapshot.snapshot_hash,
                # An auditor must be able to see whether AI touched the result.
                "ai_influenced_decisions": False,
                "note": (
                    "Match decisions are produced by deterministic rules and "
                    "feature scoring. AI output is advisory and cannot create an "
                    "approved financial action."
                ),
            },
            indent=2,
            sort_keys=True,
        ),
    )

    package.add(
        "audit-events.jsonl",
        "\n".join(
            json.dumps(event.model_dump(mode="json"), sort_keys=True, default=str)
            for event in audit_events
        ),
    )

    package.add(
        "evidence/manifest.csv",
        _csv(
            [
                {
                    "evidence_id": str(item.id),
                    "filename": item.filename,
                    "mime_type": item.mime_type,
                    "byte_size": item.byte_size,
                    "sha256": item.sha256,
                    "storage_key": item.storage_key,
                    "uploaded_by": str(item.uploaded_by),
                    "uploaded_at": item.uploaded_at.isoformat(),
                    "retention_policy": item.retention_policy,
                    "exception_id": str(item.exception_id) if item.exception_id else "",
                    "match_group_id": (
                        str(item.match_group_id) if item.match_group_id else ""
                    ),
                }
                for item in sorted(evidence, key=lambda e: str(e.id))
            ],
            [
                "evidence_id",
                "filename",
                "mime_type",
                "byte_size",
                "sha256",
                "storage_key",
                "uploaded_by",
                "uploaded_at",
                "retention_policy",
                "exception_id",
                "match_group_id",
            ],
        ),
    )

    package.add("manifest.json", package.manifest_json())
    return package
