"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-05 18:00:12.761896
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from apps.api.app.infrastructure.types import GUID, JSONColumn, Money

revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('ai_policy', sa.String(length=32), nullable=False),
    sa.Column('ai_allowed_regions', JSONColumn, nullable=False),
    sa.Column('data_region', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('ai_calls',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('task', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('policy', sa.String(length=32), nullable=False),
    sa.Column('redacted_field_count', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('cost_usd', Money(), nullable=False),
    sa.Column('schema_valid', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.String(length=512), nullable=False),
    sa.Column('user_decision', sa.String(length=16), nullable=False),
    sa.Column('subject_type', sa.String(length=64), nullable=True),
    sa.Column('subject_id', GUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_calls_tenant_id'), 'ai_calls', ['tenant_id'], unique=False)
    op.create_index('ix_ai_calls_tenant_time', 'ai_calls', ['tenant_id', 'occurred_at'], unique=False)
    op.create_table('audit_events',
    sa.Column('event_id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', GUID(), nullable=True),
    sa.Column('actor_label', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', GUID(), nullable=True),
    sa.Column('before_hash', sa.String(length=64), nullable=False),
    sa.Column('after_hash', sa.String(length=64), nullable=False),
    sa.Column('previous_event_hash', sa.String(length=64), nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('correlation_id', GUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('event_metadata', JSONColumn, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('tenant_id', 'sequence', name='uq_audit_tenant_sequence')
    )
    op.create_index('ix_audit_entity', 'audit_events', ['tenant_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_index('ix_audit_sequence', 'audit_events', ['tenant_id', 'sequence'], unique=False)
    op.create_index('ix_audit_tenant_time', 'audit_events', ['tenant_id', 'occurred_at'], unique=False)
    op.create_table('connections',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('connector_type', sa.String(length=64), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('state_detail', sa.Text(), nullable=True),
    sa.Column('cursor', sa.String(length=512), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', JSONColumn, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_connections_tenant_slug')
    )
    op.create_index(op.f('ix_connections_tenant_id'), 'connections', ['tenant_id'], unique=False)
    op.create_table('entity_aliases',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('entity_id', GUID(), nullable=False),
    sa.Column('entity_name', sa.String(length=512), nullable=False),
    sa.Column('alias', sa.String(length=512), nullable=False),
    sa.Column('normalized_alias', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('approved_by', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'normalized_alias', name='uq_alias_tenant_value')
    )
    op.create_index(op.f('ix_entity_aliases_tenant_id'), 'entity_aliases', ['tenant_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', JSONColumn, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'endpoint', 'key', name='uq_idempotency_identity')
    )
    op.create_index(op.f('ix_idempotency_keys_tenant_id'), 'idempotency_keys', ['tenant_id'], unique=False)
    op.create_table('matching_rule_sets',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('definition', JSONColumn, nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug', 'version', name='uq_rule_sets_identity')
    )
    op.create_index(op.f('ix_matching_rule_sets_tenant_id'), 'matching_rule_sets', ['tenant_id'], unique=False)
    op.create_table('period_locks',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('locked_by', GUID(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_period_locks_entity', 'period_locks', ['tenant_id', 'entity'], unique=False)
    op.create_index(op.f('ix_period_locks_tenant_id'), 'period_locks', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('external_subject', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('approval_limit', Money(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email'),
    sa.UniqueConstraint('tenant_id', 'external_subject', name='uq_users_tenant_subject')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('connector_credentials',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('connection_id', GUID(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('kms_key_id', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'kind', name='uq_credentials_connection_kind')
    )
    op.create_index(op.f('ix_connector_credentials_connection_id'), 'connector_credentials', ['connection_id'], unique=False)
    op.create_index(op.f('ix_connector_credentials_tenant_id'), 'connector_credentials', ['tenant_id'], unique=False)
    op.create_table('reconciliation_definitions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template', sa.String(length=64), nullable=True),
    sa.Column('config', JSONColumn, nullable=False),
    sa.Column('config_version', sa.String(length=32), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('rule_set_id', GUID(), nullable=True),
    sa.Column('side_a_connection_id', GUID(), nullable=True),
    sa.Column('side_b_connection_id', GUID(), nullable=True),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rule_set_id'], ['matching_rule_sets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_reconciliations_tenant_slug')
    )
    op.create_index(op.f('ix_reconciliation_definitions_tenant_id'), 'reconciliation_definitions', ['tenant_id'], unique=False)
    op.create_table('source_files',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('connection_id', GUID(), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('encoding', sa.String(length=32), nullable=True),
    sa.Column('delimiter', sa.String(length=8), nullable=True),
    sa.Column('sheet_name', sa.String(length=255), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('profile', JSONColumn, nullable=True),
    sa.Column('mapping', JSONColumn, nullable=True),
    sa.Column('quality_report', JSONColumn, nullable=True),
    sa.Column('malware_scan', sa.String(length=32), nullable=False),
    sa.Column('uploaded_by', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'checksum', name='uq_source_files_tenant_checksum')
    )
    op.create_index(op.f('ix_source_files_tenant_id'), 'source_files', ['tenant_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('role', sa.String(length=48), nullable=False),
    sa.Column('granted_by', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role', name='uq_user_roles_user_role')
    )
    op.create_index(op.f('ix_user_roles_tenant_id'), 'user_roles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('reconciliation_runs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('reconciliation_id', GUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('initiated_by', GUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('result_hash', sa.String(length=64), nullable=True),
    sa.Column('summary', JSONColumn, nullable=True),
    sa.Column('close_certificate', JSONColumn, nullable=True),
    sa.Column('closed_by', GUID(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reopen_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_id'], ['reconciliation_definitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_runs_tenant_idempotency')
    )
    op.create_index(op.f('ix_reconciliation_runs_tenant_id'), 'reconciliation_runs', ['tenant_id'], unique=False)
    op.create_index('ix_runs_tenant_reconciliation', 'reconciliation_runs', ['tenant_id', 'reconciliation_id'], unique=False)
    op.create_table('source_records',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('source_connection_id', GUID(), nullable=True),
    sa.Column('source_file_id', GUID(), nullable=True),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('payload', JSONColumn, nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_system', 'source_record_id', 'checksum', name='uq_source_records_identity')
    )
    op.create_index('ix_source_records_file', 'source_records', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_source_records_tenant_id'), 'source_records', ['tenant_id'], unique=False)
    op.create_table('candidate_matches',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('run_id', GUID(), nullable=False),
    sa.Column('side_a_ids', JSONColumn, nullable=False),
    sa.Column('side_b_ids', JSONColumn, nullable=False),
    sa.Column('cardinality', sa.String(length=8), nullable=False),
    sa.Column('generated_by', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('features', JSONColumn, nullable=False),
    sa.Column('reasons', JSONColumn, nullable=False),
    sa.Column('warnings', JSONColumn, nullable=False),
    sa.Column('rule_id', sa.String(length=128), nullable=True),
    sa.Column('rule_version', sa.String(length=32), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_matches_tenant_id'), 'candidate_matches', ['tenant_id'], unique=False)
    op.create_index('ix_candidates_run', 'candidate_matches', ['tenant_id', 'run_id'], unique=False)
    op.create_table('canonical_transactions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('source_record_row_id', GUID(), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('source_connection_id', GUID(), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('source_account_id', sa.String(length=128), nullable=True),
    sa.Column('transaction_type', sa.String(length=64), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('posting_date', sa.Date(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('amount', Money(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('debit_credit', sa.String(length=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('normalized_description', sa.Text(), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('normalized_reference', sa.String(length=255), nullable=True),
    sa.Column('external_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('bank_reference', sa.String(length=255), nullable=True),
    sa.Column('counterparty_name', sa.String(length=512), nullable=True),
    sa.Column('normalized_counterparty', sa.String(length=512), nullable=True),
    sa.Column('counterparty_account', sa.String(length=128), nullable=True),
    sa.Column('counterparty_entity_id', GUID(), nullable=True),
    sa.Column('customer_id', sa.String(length=128), nullable=True),
    sa.Column('vendor_id', sa.String(length=128), nullable=True),
    sa.Column('invoice_number', sa.String(length=128), nullable=True),
    sa.Column('normalized_invoice_number', sa.String(length=128), nullable=True),
    sa.Column('purchase_order', sa.String(length=128), nullable=True),
    sa.Column('check_number', sa.String(length=64), nullable=True),
    sa.Column('batch_id', sa.String(length=128), nullable=True),
    sa.Column('settlement_id', sa.String(length=128), nullable=True),
    sa.Column('payout_id', sa.String(length=128), nullable=True),
    sa.Column('gross_amount', Money(), nullable=True),
    sa.Column('fee_amount', Money(), nullable=True),
    sa.Column('tax_amount', Money(), nullable=True),
    sa.Column('net_amount', Money(), nullable=True),
    sa.Column('original_amount', Money(), nullable=True),
    sa.Column('original_currency', sa.String(length=3), nullable=True),
    sa.Column('functional_amount', Money(), nullable=True),
    sa.Column('functional_currency', sa.String(length=3), nullable=True),
    sa.Column('fx_rate', Money(), nullable=True),
    sa.Column('fx_rate_source', sa.String(length=128), nullable=True),
    sa.Column('fx_rate_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('document_refs', JSONColumn, nullable=False),
    sa.Column('tags', JSONColumn, nullable=False),
    sa.Column('raw_payload', JSONColumn, nullable=False),
    sa.Column('source_checksum', sa.String(length=64), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reversal_of_transaction_id', GUID(), nullable=True),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.CheckConstraint('length(currency) = 3', name='ck_tx_currency_length'),
    sa.ForeignKeyConstraint(['source_record_row_id'], ['source_records.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_connection_id', 'source_record_id', 'source_checksum', name='uq_transactions_identity')
    )
    op.create_index(op.f('ix_canonical_transactions_tenant_id'), 'canonical_transactions', ['tenant_id'], unique=False)
    op.create_index('ix_tx_tenant_amount', 'canonical_transactions', ['tenant_id', 'currency', 'amount'], unique=False)
    op.create_index('ix_tx_tenant_connection', 'canonical_transactions', ['tenant_id', 'source_connection_id'], unique=False)
    op.create_index('ix_tx_tenant_counterparty', 'canonical_transactions', ['tenant_id', 'normalized_counterparty'], unique=False)
    op.create_index('ix_tx_tenant_currency_date', 'canonical_transactions', ['tenant_id', 'currency', 'transaction_date'], unique=False)
    op.create_index('ix_tx_tenant_external', 'canonical_transactions', ['tenant_id', 'external_transaction_id'], unique=False)
    op.create_index('ix_tx_tenant_invoice', 'canonical_transactions', ['tenant_id', 'normalized_invoice_number'], unique=False)
    op.create_index('ix_tx_tenant_reference', 'canonical_transactions', ['tenant_id', 'normalized_reference'], unique=False)
    op.create_index('ix_tx_tenant_settlement', 'canonical_transactions', ['tenant_id', 'settlement_id'], unique=False)
    op.create_table('exceptions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('reconciliation_run_id', GUID(), nullable=False),
    sa.Column('transaction_ids', JSONColumn, nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('amount_exposure', Money(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('reason_codes', JSONColumn, nullable=False),
    sa.Column('owner_user_id', GUID(), nullable=True),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proposed_resolution', sa.Text(), nullable=True),
    sa.Column('resolution_code', sa.String(length=64), nullable=True),
    sa.Column('proposed_by_actor_type', sa.String(length=32), nullable=True),
    sa.Column('ai_suggestion_id', GUID(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('closed_by', GUID(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['reconciliation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exceptions_owner', 'exceptions', ['tenant_id', 'owner_user_id'], unique=False)
    op.create_index('ix_exceptions_run', 'exceptions', ['tenant_id', 'reconciliation_run_id'], unique=False)
    op.create_index('ix_exceptions_status', 'exceptions', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_exceptions_tenant_id'), 'exceptions', ['tenant_id'], unique=False)
    op.create_table('match_groups',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('run_id', GUID(), nullable=False),
    sa.Column('reconciliation_id', GUID(), nullable=False),
    sa.Column('cardinality', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_amount', Money(), nullable=False),
    sa.Column('rule_id', sa.String(length=128), nullable=True),
    sa.Column('rule_version', sa.String(length=32), nullable=True),
    sa.Column('rule_set_version', sa.String(length=32), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('engine_stage', sa.String(length=32), nullable=False),
    sa.Column('reasons', JSONColumn, nullable=False),
    sa.Column('warnings', JSONColumn, nullable=False),
    sa.Column('competing_candidate_count', sa.Integer(), nullable=False),
    sa.Column('extra', JSONColumn, nullable=False),
    sa.Column('created_by_actor_type', sa.String(length=32), nullable=False),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('approved_by', GUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by', GUID(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_match_groups_run', 'match_groups', ['tenant_id', 'run_id'], unique=False)
    op.create_index('ix_match_groups_status', 'match_groups', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_match_groups_tenant_id'), 'match_groups', ['tenant_id'], unique=False)
    op.create_table('run_transaction_snapshots',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('run_id', GUID(), nullable=False),
    sa.Column('side_a_transaction_ids', JSONColumn, nullable=False),
    sa.Column('side_b_transaction_ids', JSONColumn, nullable=False),
    sa.Column('source_checksums', JSONColumn, nullable=False),
    sa.Column('rule_set_version', sa.String(length=32), nullable=False),
    sa.Column('rule_versions', JSONColumn, nullable=False),
    sa.Column('config_version', sa.String(length=32), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('fx_rate_source', sa.String(length=128), nullable=True),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index(op.f('ix_run_transaction_snapshots_tenant_id'), 'run_transaction_snapshots', ['tenant_id'], unique=False)
    op.create_table('accounting_action_proposals',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('exception_id', GUID(), nullable=True),
    sa.Column('run_id', GUID(), nullable=True),
    sa.Column('journal_date', sa.String(length=32), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('lines', JSONColumn, nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('preparer_id', GUID(), nullable=False),
    sa.Column('required_approver_role', sa.String(length=48), nullable=False),
    sa.Column('approver_id', GUID(), nullable=True),
    sa.Column('ai_assisted', sa.Boolean(), nullable=False),
    sa.Column('ai_suggestion_id', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounting_action_proposals_tenant_id'), 'accounting_action_proposals', ['tenant_id'], unique=False)
    op.create_index('ix_proposals_run', 'accounting_action_proposals', ['tenant_id', 'run_id'], unique=False)
    op.create_table('exception_comments',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('exception_id', GUID(), nullable=False),
    sa.Column('author_id', GUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comments_exception', 'exception_comments', ['tenant_id', 'exception_id'], unique=False)
    op.create_index(op.f('ix_exception_comments_tenant_id'), 'exception_comments', ['tenant_id'], unique=False)
    op.create_table('exception_evidence',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('exception_id', GUID(), nullable=True),
    sa.Column('match_group_id', GUID(), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('retention_policy', sa.String(length=64), nullable=False),
    sa.Column('extraction', JSONColumn, nullable=True),
    sa.Column('uploaded_by', GUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_exception', 'exception_evidence', ['tenant_id', 'exception_id'], unique=False)
    op.create_index('ix_evidence_match', 'exception_evidence', ['tenant_id', 'match_group_id'], unique=False)
    op.create_index(op.f('ix_exception_evidence_tenant_id'), 'exception_evidence', ['tenant_id'], unique=False)
    op.create_table('match_group_members',
    sa.Column('match_group_id', GUID(), nullable=False),
    sa.Column('transaction_id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('side', sa.String(length=1), nullable=False),
    sa.Column('allocated_amount', Money(), nullable=False),
    sa.CheckConstraint("side IN ('A', 'B')", name='ck_member_side'),
    sa.ForeignKeyConstraint(['match_group_id'], ['match_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('match_group_id', 'transaction_id')
    )
    op.create_index(op.f('ix_match_group_members_tenant_id'), 'match_group_members', ['tenant_id'], unique=False)
    op.create_index('ix_members_transaction', 'match_group_members', ['tenant_id', 'transaction_id'], unique=False)
    op.create_table('transaction_lineage',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('transaction_id', GUID(), nullable=False),
    sa.Column('canonical_field', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('source_field', sa.String(length=255), nullable=False),
    sa.Column('transformation', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['canonical_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lineage_transaction', 'transaction_lineage', ['tenant_id', 'transaction_id'], unique=False)
    op.create_index(op.f('ix_transaction_lineage_tenant_id'), 'transaction_lineage', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_lineage_tenant_id'), table_name='transaction_lineage')
    op.drop_index('ix_lineage_transaction', table_name='transaction_lineage')
    op.drop_table('transaction_lineage')
    op.drop_index('ix_members_transaction', table_name='match_group_members')
    op.drop_index(op.f('ix_match_group_members_tenant_id'), table_name='match_group_members')
    op.drop_table('match_group_members')
    op.drop_index(op.f('ix_exception_evidence_tenant_id'), table_name='exception_evidence')
    op.drop_index('ix_evidence_match', table_name='exception_evidence')
    op.drop_index('ix_evidence_exception', table_name='exception_evidence')
    op.drop_table('exception_evidence')
    op.drop_index(op.f('ix_exception_comments_tenant_id'), table_name='exception_comments')
    op.drop_index('ix_comments_exception', table_name='exception_comments')
    op.drop_table('exception_comments')
    op.drop_index('ix_proposals_run', table_name='accounting_action_proposals')
    op.drop_index(op.f('ix_accounting_action_proposals_tenant_id'), table_name='accounting_action_proposals')
    op.drop_table('accounting_action_proposals')
    op.drop_index(op.f('ix_run_transaction_snapshots_tenant_id'), table_name='run_transaction_snapshots')
    op.drop_table('run_transaction_snapshots')
    op.drop_index(op.f('ix_match_groups_tenant_id'), table_name='match_groups')
    op.drop_index('ix_match_groups_status', table_name='match_groups')
    op.drop_index('ix_match_groups_run', table_name='match_groups')
    op.drop_table('match_groups')
    op.drop_index(op.f('ix_exceptions_tenant_id'), table_name='exceptions')
    op.drop_index('ix_exceptions_status', table_name='exceptions')
    op.drop_index('ix_exceptions_run', table_name='exceptions')
    op.drop_index('ix_exceptions_owner', table_name='exceptions')
    op.drop_table('exceptions')
    op.drop_index('ix_tx_tenant_settlement', table_name='canonical_transactions')
    op.drop_index('ix_tx_tenant_reference', table_name='canonical_transactions')
    op.drop_index('ix_tx_tenant_invoice', table_name='canonical_transactions')
    op.drop_index('ix_tx_tenant_external', table_name='canonical_transactions')
    op.drop_index('ix_tx_tenant_currency_date', table_name='canonical_transactions')
    op.drop_index('ix_tx_tenant_counterparty', table_name='canonical_transactions')
    op.drop_index('ix_tx_tenant_connection', table_name='canonical_transactions')
    op.drop_index('ix_tx_tenant_amount', table_name='canonical_transactions')
    op.drop_index(op.f('ix_canonical_transactions_tenant_id'), table_name='canonical_transactions')
    op.drop_table('canonical_transactions')
    op.drop_index('ix_candidates_run', table_name='candidate_matches')
    op.drop_index(op.f('ix_candidate_matches_tenant_id'), table_name='candidate_matches')
    op.drop_table('candidate_matches')
    op.drop_index(op.f('ix_source_records_tenant_id'), table_name='source_records')
    op.drop_index('ix_source_records_file', table_name='source_records')
    op.drop_table('source_records')
    op.drop_index('ix_runs_tenant_reconciliation', table_name='reconciliation_runs')
    op.drop_index(op.f('ix_reconciliation_runs_tenant_id'), table_name='reconciliation_runs')
    op.drop_table('reconciliation_runs')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_tenant_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_source_files_tenant_id'), table_name='source_files')
    op.drop_table('source_files')
    op.drop_index(op.f('ix_reconciliation_definitions_tenant_id'), table_name='reconciliation_definitions')
    op.drop_table('reconciliation_definitions')
    op.drop_index(op.f('ix_connector_credentials_tenant_id'), table_name='connector_credentials')
    op.drop_index(op.f('ix_connector_credentials_connection_id'), table_name='connector_credentials')
    op.drop_table('connector_credentials')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_period_locks_tenant_id'), table_name='period_locks')
    op.drop_index('ix_period_locks_entity', table_name='period_locks')
    op.drop_table('period_locks')
    op.drop_index(op.f('ix_matching_rule_sets_tenant_id'), table_name='matching_rule_sets')
    op.drop_table('matching_rule_sets')
    op.drop_index(op.f('ix_idempotency_keys_tenant_id'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_entity_aliases_tenant_id'), table_name='entity_aliases')
    op.drop_table('entity_aliases')
    op.drop_index(op.f('ix_connections_tenant_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_index('ix_audit_tenant_time', table_name='audit_events')
    op.drop_index('ix_audit_sequence', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index('ix_audit_entity', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_ai_calls_tenant_time', table_name='ai_calls')
    op.drop_index(op.f('ix_ai_calls_tenant_id'), table_name='ai_calls')
    op.drop_table('ai_calls')
    op.drop_table('tenants')
    # ### end Alembic commands ###
