#!/usr/bin/env python
"""Generate Prometheus alert rules from the Python source of truth."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from packages.observability.alerts import ALERT_RULES, Severity  # noqa: E402

OUTPUT = ROOT / "infra" / "monitoring" / "alerts.yml"


def quoted(value: str) -> str:
    """JSON strings are valid YAML strings and need no YAML dependency."""
    return json.dumps(value, ensure_ascii=False)


def prometheus_expression(metric: str, operator: str, threshold: float) -> str:
    symbol = ">" if operator == "gt" else "<"
    rendered = str(int(threshold)) if threshold.is_integer() else str(threshold)
    return f"{metric} {symbol} {rendered}"


def render() -> str:
    severity = {Severity.PAGE: "critical", Severity.TICKET: "warning", Severity.REVIEW: "info"}
    lines = [
        "# Generated by scripts/generate_monitoring_config.py; do not edit by hand.",
        "groups:",
        "  - name: reconciliation-platform",
        "    rules:",
    ]
    for rule in ALERT_RULES:
        expression = prometheus_expression(rule.metric, rule.operator, rule.threshold)
        lines.extend(
            [
                f"      - alert: {rule.name}",
                f"        expr: {expression}",
                "        for: 5m",
                "        labels:",
                f"          severity: {severity[rule.severity]}",
                "        annotations:",
                f"          summary: {quoted(rule.question)}",
                f"          threshold: {quoted(rule.threshold_description)}",
                f"          first_action: {quoted(rule.first_action)}",
                f"          runbook: {quoted(rule.runbook)}",
            ]
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(), encoding="utf-8", newline="\n")
    print(f"generated {len(ALERT_RULES)} rules in {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
